---
title: "MuDyMust - Modelling"
author: "Küng, P., Höhener, P.S., Vieth, G., Spliesgart, A., Scholz, U., Rothman, A., Simpson, J."
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    theme: flatly
    df_print: kable
    toc: yes
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: show
    toc_depth: 5
    highlight: tango
---


# Setup

```{r setup, message = FALSE, warning = FALSE, results = 'hide'}

library(tidyverse)
library(easystats)
library(cmdstanr)
library(knitr)
library(brms)
#install.packages("cmdstanr", repos = c('https://stan-dev.r-universe.dev', getOption("repos")))
#cmdstanr::check_cmdstan_toolchain(fix = TRUE)
#cmdstanr::install_cmdstan()
library(remotes)
#remotes::install_github('Pascal-kueng/wbCorr')
library(wbCorr)

source(file.path('Functions', 'PrettyTables.R'))
source(file.path('Functions', 'ReportModels.R'))
source(file.path('Functions', 'ReportMeasures.R'))
source(file.path('Functions', 'HurdleGaussianFamily.R'))

```


Setting general parameters
```{r}

system("shutdown /a") # prevent previously initialized shutdowns
shutdown = FALSE # restart after script finished or an error occurred (can be stoped within 180 seconds with command above)
check_models = TRUE 
get_bayesfactor = FALSE 

if (get_bayesfactor) {
  stats_to_report <- c('CI', 'SE', 'pd', 'ROPE', 'BF', 'Rhat', 'ESS')
} else {
  stats_to_report <- c('CI', 'SE', 'pd', 'ROPE', 'Rhat', 'ESS')
}

options(
  brms.backend = 'cmdstan',
  brms.file_refit = 'on_change',
  #brms.file_refit = 'always',
  error = function() {
    beepr::beep(sound = 5)
    if (shutdown) {
      system("shutdown /s /t 180")
      quit(save = "no", status = 1)
    }
  }
  , es.use_symbols = TRUE
)


```


Set model parameters
```{r}

iterations = 2000 # final models 12'000 per chain to achieve 40'000 needed for BF
warmup = 1000 # 2000 on final models

```


# Load merged dataset

```{r}

temp_script <- tempfile(fileext = ".R")
knitr::purl("01_harmonize_datasets.Rmd", output = temp_script)
source(temp_script)

head(df_merged) 

```

# Plot distributions of predictors

```{r}

hist(df_merged$emo_support)
hist(df_merged$pract_support)
hist(df_merged$pos_control)
hist(df_merged$neg_control)


```
# Plot MVPA

```{r}

hist(df_merged$mvpa, breaks=200)
plot(df_merged$day, df_merged$mvpa)
plot(df_merged$studyID, df_merged$mvpa)
plot(df_merged$dyad_type, df_merged$mvpa)

```


# Bivariate correlations

```{r}

cors <- wbCorr(
  df_merged, 
  cluster = 'id', 
  method = 'spearman'
)

summary(cors, 'wb')

```



# Modelling

## Positive Control

```{r}

## Support
formula_emo_support <- bf(
  mvpa ~ (pos_control_cw + pos_control_cb) * dyad_type + 
    (1 + pos_control_cw | studyID/id),
  family = negbinomial()
)

#prior1 <- !todo: define priors

model_support_emo <- brm(
  formula_emo_support, 
  #prior = prior1,
  data = df_merged, 
  chains = 4, 
  iter = 2000, 
  warmup = 1000, 
  cores = 4, 
  backend = 'cmdstan',
  file = file.path('models_cache', 'support_emo')
)

summary(model_support_emo)
check_brms(model_support_emo)



```








